<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6a7c22ea50c000fac92f5e1384f4e4e6
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Portfolio\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Portfolio\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6a7c22ea50c000fac92f5e1384f4e4e6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6a7c22ea50c000fac92f5e1384f4e4e6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6a7c22ea50c000fac92f5e1384f4e4e6::$classMap;

        }, null, ClassLoader::class);
    }
}
